# shellcheck shell=fish
# =============================================================================
# kubectl-aliases — 由 Go 生成器自动生成，请勿手动编辑
# 源文件: main.go
# =============================================================================
# 自动生成 691 条 kubectl 别名，覆盖 9 种资源 × 3 个动词 × 格式/范围修饰符
# 通过组合生成器动态构造，无需手工维护。fish 都能用。
#
# 命名规则: k[作用域][动词][资源][修饰符]
#   作用域  '' / sys（kube-system）
#   动词    g / d / del / l / ex / pf
#   修饰符  oyaml / owide / ojson / sl / w / all / n / l / f
#   示例    kgpooyamlall = kubectl get pods -o=yaml --all-namespaces
#           kdelnow      = kubectl delete --grace-period=0 --force
#           kl           = kubectl logs（不带资源类型，直接写 pod 名）
# =============================================================================

if set -q _K8S_ALIAS_LOADED; exit 0; end
set -g _K8S_ALIAS_LOADED 1

abbr --add k "kubectl"


# ==============================================================================
# kubectl aliases — 自动生成（按类别分组）
# ==============================================================================


# ── kubectl run ──
abbr --add krun "kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add ksysrun "kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t --namespace=kube-system"
abbr --add krunn "kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t --namespace"

# ── kubectl apply ──
abbr --add ka "kubectl apply --recursive -f"
abbr --add ksysa "kubectl apply --recursive -f --namespace=kube-system"

# ── kubectl kustomize ──
abbr --add kak "kubectl apply -k"
abbr --add kk "kubectl kustomize"

# ── kubectl delete（强制/递归） ──
abbr --add kdelnow "kubectl delete --grace-period=0 --force"
abbr --add ksysdelnow "kubectl delete --grace-period=0 --force --namespace=kube-system"
abbr --add kdelf "kubectl delete --recursive -f"
abbr --add kdelall "kubectl delete --all"
abbr --add ksysdelall "kubectl delete --all --namespace=kube-system"

# ── kubectl get/describe -f ──
abbr --add kgf "kubectl get --recursive -f"
abbr --add kdf "kubectl describe --recursive -f"

# ── 动词独立 + 格式（无资源） ──
abbr --add kgoyamlf "kubectl get -o=yaml --recursive -f"
abbr --add kgowidef "kubectl get -o=wide --recursive -f"
abbr --add kgojsonf "kubectl get -o=json --recursive -f"
abbr --add kgslf "kubectl get --show-labels --recursive -f"
abbr --add kgwf "kubectl get --watch --recursive -f"
abbr --add kgowideslf "kubectl get -o=wide --show-labels --recursive -f"
abbr --add kgslowidef "kubectl get --show-labels -o=wide --recursive -f"
abbr --add kgslwf "kubectl get --show-labels --watch --recursive -f"
abbr --add kgwslf "kubectl get --watch --show-labels --recursive -f"
abbr --add kgoyaml "kubectl get -o=yaml"
abbr --add kgowide "kubectl get -o=wide"
abbr --add kgojson "kubectl get -o=json"
abbr --add kgsl "kubectl get --show-labels"
abbr --add kgw "kubectl get --watch"
abbr --add kgoyamlall "kubectl get -o=yaml --all-namespaces"
abbr --add kgowideall "kubectl get -o=wide --all-namespaces"
abbr --add kgojsonall "kubectl get -o=json --all-namespaces"
abbr --add kgall "kubectl get --all-namespaces"
abbr --add kdall "kubectl describe --all-namespaces"
abbr --add kgalloyaml "kubectl get --all-namespaces -o=yaml"
abbr --add kgallowide "kubectl get --all-namespaces -o=wide"
abbr --add kgallojson "kubectl get --all-namespaces -o=json"
abbr --add kgallsl "kubectl get --all-namespaces --show-labels"
abbr --add kgallw "kubectl get --all-namespaces --watch"
abbr --add kgslall "kubectl get --show-labels --all-namespaces"
abbr --add kgwall "kubectl get --watch --all-namespaces"
abbr --add kgoyamln "kubectl get -o=yaml --namespace"
abbr --add kgowiden "kubectl get -o=wide --namespace"
abbr --add kgojsonn "kubectl get -o=json --namespace"
abbr --add kgsln "kubectl get --show-labels --namespace"
abbr --add kgwn "kubectl get --watch --namespace"
abbr --add kgoyamll "kubectl get -o=yaml -l"
abbr --add kgowidel "kubectl get -o=wide -l"
abbr --add kgojsonl "kubectl get -o=json -l"
abbr --add kgsll "kubectl get --show-labels -l"
abbr --add kgwl "kubectl get --watch -l"

# ── logs / exec / port-forward（无资源类型） ──
abbr --add kl "kubectl logs"
abbr --add klf "kubectl logs -f"
abbr --add kltt "kubectl logs --tail=50 -f"
abbr --add kpf "kubectl port-forward"
abbr --add kex "kubectl exec -i -t"
abbr --add kp "kubectl proxy"
abbr --add kexn "kubectl exec -i -t --namespace"
abbr --add klfn "kubectl logs -f --namespace"
abbr --add kpfn "kubectl port-forward --namespace"

# ── kube-system → get ──
abbr --add ksysg "kubectl get --namespace=kube-system"
abbr --add ksysgl "kubectl --namespace=kube-system get -l"
abbr --add ksysgf "kubectl --namespace=kube-system get --recursive -f"
abbr --add ksysgpo "kubectl --namespace=kube-system get pods"
abbr --add ksysgpol "kubectl --namespace=kube-system get pods -l"
abbr --add ksysgpooyaml "kubectl --namespace=kube-system get pods -o=yaml"
abbr --add ksysgpooyamll "kubectl --namespace=kube-system get pods -o=yaml -l"
abbr --add ksysgpoowide "kubectl --namespace=kube-system get pods -o=wide"
abbr --add ksysgpoowidel "kubectl --namespace=kube-system get pods -o=wide -l"
abbr --add ksysgpoojson "kubectl --namespace=kube-system get pods -o=json"
abbr --add ksysgpoojsonl "kubectl --namespace=kube-system get pods -o=json -l"
abbr --add ksysgposl "kubectl --namespace=kube-system get pods --show-labels"
abbr --add ksysgposll "kubectl --namespace=kube-system get pods --show-labels -l"
abbr --add ksysgpow "kubectl --namespace=kube-system get pods --watch"
abbr --add ksysgpowl "kubectl --namespace=kube-system get pods --watch -l"
abbr --add ksysgdep "kubectl --namespace=kube-system get deployment"
abbr --add ksysgdepl "kubectl --namespace=kube-system get deployment -l"
abbr --add ksysgdepoyaml "kubectl --namespace=kube-system get deployment -o=yaml"
abbr --add ksysgdepoyamll "kubectl --namespace=kube-system get deployment -o=yaml -l"
abbr --add ksysgdepowide "kubectl --namespace=kube-system get deployment -o=wide"
abbr --add ksysgdepowidel "kubectl --namespace=kube-system get deployment -o=wide -l"
abbr --add ksysgdepojson "kubectl --namespace=kube-system get deployment -o=json"
abbr --add ksysgdepojsonl "kubectl --namespace=kube-system get deployment -o=json -l"
abbr --add ksysgdepsl "kubectl --namespace=kube-system get deployment --show-labels"
abbr --add ksysgdepsll "kubectl --namespace=kube-system get deployment --show-labels -l"
abbr --add ksysgdepw "kubectl --namespace=kube-system get deployment --watch"
abbr --add ksysgdepwl "kubectl --namespace=kube-system get deployment --watch -l"
abbr --add ksysgsts "kubectl --namespace=kube-system get statefulset"
abbr --add ksysgstsl "kubectl --namespace=kube-system get statefulset -l"
abbr --add ksysgstsoyaml "kubectl --namespace=kube-system get statefulset -o=yaml"
abbr --add ksysgstsoyamll "kubectl --namespace=kube-system get statefulset -o=yaml -l"
abbr --add ksysgstsowide "kubectl --namespace=kube-system get statefulset -o=wide"
abbr --add ksysgstsowidel "kubectl --namespace=kube-system get statefulset -o=wide -l"
abbr --add ksysgstsojson "kubectl --namespace=kube-system get statefulset -o=json"
abbr --add ksysgstsojsonl "kubectl --namespace=kube-system get statefulset -o=json -l"
abbr --add ksysgstssl "kubectl --namespace=kube-system get statefulset --show-labels"
abbr --add ksysgstssll "kubectl --namespace=kube-system get statefulset --show-labels -l"
abbr --add ksysgstsw "kubectl --namespace=kube-system get statefulset --watch"
abbr --add ksysgstswl "kubectl --namespace=kube-system get statefulset --watch -l"
abbr --add ksysgsvc "kubectl --namespace=kube-system get service"
abbr --add ksysgsvcl "kubectl --namespace=kube-system get service -l"
abbr --add ksysgsvcoyaml "kubectl --namespace=kube-system get service -o=yaml"
abbr --add ksysgsvcoyamll "kubectl --namespace=kube-system get service -o=yaml -l"
abbr --add ksysgsvcowide "kubectl --namespace=kube-system get service -o=wide"
abbr --add ksysgsvcowidel "kubectl --namespace=kube-system get service -o=wide -l"
abbr --add ksysgsvcojson "kubectl --namespace=kube-system get service -o=json"
abbr --add ksysgsvcojsonl "kubectl --namespace=kube-system get service -o=json -l"
abbr --add ksysgsvcsl "kubectl --namespace=kube-system get service --show-labels"
abbr --add ksysgsvcsll "kubectl --namespace=kube-system get service --show-labels -l"
abbr --add ksysgsvcw "kubectl --namespace=kube-system get service --watch"
abbr --add ksysgsvcwl "kubectl --namespace=kube-system get service --watch -l"
abbr --add ksysging "kubectl --namespace=kube-system get ingress"
abbr --add ksysgingl "kubectl --namespace=kube-system get ingress -l"
abbr --add ksysgingoyaml "kubectl --namespace=kube-system get ingress -o=yaml"
abbr --add ksysgingoyamll "kubectl --namespace=kube-system get ingress -o=yaml -l"
abbr --add ksysgingowide "kubectl --namespace=kube-system get ingress -o=wide"
abbr --add ksysgingowidel "kubectl --namespace=kube-system get ingress -o=wide -l"
abbr --add ksysgingojson "kubectl --namespace=kube-system get ingress -o=json"
abbr --add ksysgingojsonl "kubectl --namespace=kube-system get ingress -o=json -l"
abbr --add ksysgingsl "kubectl --namespace=kube-system get ingress --show-labels"
abbr --add ksysgingsll "kubectl --namespace=kube-system get ingress --show-labels -l"
abbr --add ksysgingw "kubectl --namespace=kube-system get ingress --watch"
abbr --add ksysgingwl "kubectl --namespace=kube-system get ingress --watch -l"
abbr --add ksysgcm "kubectl --namespace=kube-system get configmap"
abbr --add ksysgcml "kubectl --namespace=kube-system get configmap -l"
abbr --add ksysgcmoyaml "kubectl --namespace=kube-system get configmap -o=yaml"
abbr --add ksysgcmoyamll "kubectl --namespace=kube-system get configmap -o=yaml -l"
abbr --add ksysgcmowide "kubectl --namespace=kube-system get configmap -o=wide"
abbr --add ksysgcmowidel "kubectl --namespace=kube-system get configmap -o=wide -l"
abbr --add ksysgcmojson "kubectl --namespace=kube-system get configmap -o=json"
abbr --add ksysgcmojsonl "kubectl --namespace=kube-system get configmap -o=json -l"
abbr --add ksysgcmsl "kubectl --namespace=kube-system get configmap --show-labels"
abbr --add ksysgcmsll "kubectl --namespace=kube-system get configmap --show-labels -l"
abbr --add ksysgcmw "kubectl --namespace=kube-system get configmap --watch"
abbr --add ksysgcmwl "kubectl --namespace=kube-system get configmap --watch -l"
abbr --add ksysgsec "kubectl --namespace=kube-system get secret"
abbr --add ksysgsecl "kubectl --namespace=kube-system get secret -l"
abbr --add ksysgsecoyaml "kubectl --namespace=kube-system get secret -o=yaml"
abbr --add ksysgsecoyamll "kubectl --namespace=kube-system get secret -o=yaml -l"
abbr --add ksysgsecowide "kubectl --namespace=kube-system get secret -o=wide"
abbr --add ksysgsecowidel "kubectl --namespace=kube-system get secret -o=wide -l"
abbr --add ksysgsecojson "kubectl --namespace=kube-system get secret -o=json"
abbr --add ksysgsecojsonl "kubectl --namespace=kube-system get secret -o=json -l"
abbr --add ksysgsecsl "kubectl --namespace=kube-system get secret --show-labels"
abbr --add ksysgsecsll "kubectl --namespace=kube-system get secret --show-labels -l"
abbr --add ksysgsecw "kubectl --namespace=kube-system get secret --watch"
abbr --add ksysgsecwl "kubectl --namespace=kube-system get secret --watch -l"

# ── kube-system → describe/delete ──
abbr --add ksysd "kubectl describe --namespace=kube-system"
abbr --add ksysdel "kubectl delete --namespace=kube-system"
abbr --add ksysdl "kubectl --namespace=kube-system describe -l"
abbr --add ksysdf "kubectl --namespace=kube-system describe --recursive -f"
abbr --add ksysdpo "kubectl --namespace=kube-system describe pods"
abbr --add ksysdpol "kubectl --namespace=kube-system describe pods -l"
abbr --add ksysddep "kubectl --namespace=kube-system describe deployment"
abbr --add ksysddepl "kubectl --namespace=kube-system describe deployment -l"
abbr --add ksysdsts "kubectl --namespace=kube-system describe statefulset"
abbr --add ksysdstsl "kubectl --namespace=kube-system describe statefulset -l"
abbr --add ksysdsvc "kubectl --namespace=kube-system describe service"
abbr --add ksysdsvcl "kubectl --namespace=kube-system describe service -l"
abbr --add ksysding "kubectl --namespace=kube-system describe ingress"
abbr --add ksysdingl "kubectl --namespace=kube-system describe ingress -l"
abbr --add ksysdcm "kubectl --namespace=kube-system describe configmap"
abbr --add ksysdcml "kubectl --namespace=kube-system describe configmap -l"
abbr --add ksysdsec "kubectl --namespace=kube-system describe secret"
abbr --add ksysdsecl "kubectl --namespace=kube-system describe secret -l"
abbr --add ksysdell "kubectl --namespace=kube-system delete -l"
abbr --add ksysdelf "kubectl --namespace=kube-system delete --recursive -f"
abbr --add ksysdelpo "kubectl --namespace=kube-system delete pods"
abbr --add ksysdelpol "kubectl --namespace=kube-system delete pods -l"
abbr --add ksysdeldep "kubectl --namespace=kube-system delete deployment"
abbr --add ksysdeldepl "kubectl --namespace=kube-system delete deployment -l"
abbr --add ksysdelsts "kubectl --namespace=kube-system delete statefulset"
abbr --add ksysdelstsl "kubectl --namespace=kube-system delete statefulset -l"
abbr --add ksysdelsvc "kubectl --namespace=kube-system delete service"
abbr --add ksysdelsvcl "kubectl --namespace=kube-system delete service -l"
abbr --add ksysdeling "kubectl --namespace=kube-system delete ingress"
abbr --add ksysdelingl "kubectl --namespace=kube-system delete ingress -l"
abbr --add ksysdelcm "kubectl --namespace=kube-system delete configmap"
abbr --add ksysdelcml "kubectl --namespace=kube-system delete configmap -l"
abbr --add ksysdelsec "kubectl --namespace=kube-system delete secret"
abbr --add ksysdelsecl "kubectl --namespace=kube-system delete secret -l"

# ── 基础 get ──
abbr --add kg "kubectl get"
abbr --add kgl "kubectl get -l"
abbr --add kgpo "kubectl get pods"
abbr --add kgpoall "kubectl get pods --all-namespaces"
abbr --add kgpon "kubectl get pods --namespace"
abbr --add kgpol "kubectl get pods -l"
abbr --add kgpooyaml "kubectl get pods -o=yaml"
abbr --add kgpooyamlall "kubectl get pods -o=yaml --all-namespaces"
abbr --add kgpooyamln "kubectl get pods -o=yaml --namespace"
abbr --add kgpooyamll "kubectl get pods -o=yaml -l"
abbr --add kgpoowide "kubectl get pods -o=wide"
abbr --add kgpoowideall "kubectl get pods -o=wide --all-namespaces"
abbr --add kgpoowiden "kubectl get pods -o=wide --namespace"
abbr --add kgpoowidel "kubectl get pods -o=wide -l"
abbr --add kgpoojson "kubectl get pods -o=json"
abbr --add kgpoojsonall "kubectl get pods -o=json --all-namespaces"
abbr --add kgpoojsonn "kubectl get pods -o=json --namespace"
abbr --add kgpoojsonl "kubectl get pods -o=json -l"
abbr --add kgposl "kubectl get pods --show-labels"
abbr --add kgposlall "kubectl get pods --show-labels --all-namespaces"
abbr --add kgposln "kubectl get pods --show-labels --namespace"
abbr --add kgposll "kubectl get pods --show-labels -l"
abbr --add kgpow "kubectl get pods --watch"
abbr --add kgpowall "kubectl get pods --watch --all-namespaces"
abbr --add kgpown "kubectl get pods --watch --namespace"
abbr --add kgpowl "kubectl get pods --watch -l"
abbr --add kgdep "kubectl get deployment"
abbr --add kgdepall "kubectl get deployment --all-namespaces"
abbr --add kgdepn "kubectl get deployment --namespace"
abbr --add kgdepl "kubectl get deployment -l"
abbr --add kgdepoyaml "kubectl get deployment -o=yaml"
abbr --add kgdepoyamlall "kubectl get deployment -o=yaml --all-namespaces"
abbr --add kgdepoyamln "kubectl get deployment -o=yaml --namespace"
abbr --add kgdepoyamll "kubectl get deployment -o=yaml -l"
abbr --add kgdepowide "kubectl get deployment -o=wide"
abbr --add kgdepowideall "kubectl get deployment -o=wide --all-namespaces"
abbr --add kgdepowiden "kubectl get deployment -o=wide --namespace"
abbr --add kgdepowidel "kubectl get deployment -o=wide -l"
abbr --add kgdepojson "kubectl get deployment -o=json"
abbr --add kgdepojsonall "kubectl get deployment -o=json --all-namespaces"
abbr --add kgdepojsonn "kubectl get deployment -o=json --namespace"
abbr --add kgdepojsonl "kubectl get deployment -o=json -l"
abbr --add kgdepsl "kubectl get deployment --show-labels"
abbr --add kgdepslall "kubectl get deployment --show-labels --all-namespaces"
abbr --add kgdepsln "kubectl get deployment --show-labels --namespace"
abbr --add kgdepsll "kubectl get deployment --show-labels -l"
abbr --add kgdepw "kubectl get deployment --watch"
abbr --add kgdepwall "kubectl get deployment --watch --all-namespaces"
abbr --add kgdepwn "kubectl get deployment --watch --namespace"
abbr --add kgdepwl "kubectl get deployment --watch -l"
abbr --add kgsts "kubectl get statefulset"
abbr --add kgstsall "kubectl get statefulset --all-namespaces"
abbr --add kgstsn "kubectl get statefulset --namespace"
abbr --add kgstsl "kubectl get statefulset -l"
abbr --add kgstsoyaml "kubectl get statefulset -o=yaml"
abbr --add kgstsoyamlall "kubectl get statefulset -o=yaml --all-namespaces"
abbr --add kgstsoyamln "kubectl get statefulset -o=yaml --namespace"
abbr --add kgstsoyamll "kubectl get statefulset -o=yaml -l"
abbr --add kgstsowide "kubectl get statefulset -o=wide"
abbr --add kgstsowideall "kubectl get statefulset -o=wide --all-namespaces"
abbr --add kgstsowiden "kubectl get statefulset -o=wide --namespace"
abbr --add kgstsowidel "kubectl get statefulset -o=wide -l"
abbr --add kgstsojson "kubectl get statefulset -o=json"
abbr --add kgstsojsonall "kubectl get statefulset -o=json --all-namespaces"
abbr --add kgstsojsonn "kubectl get statefulset -o=json --namespace"
abbr --add kgstsojsonl "kubectl get statefulset -o=json -l"
abbr --add kgstssl "kubectl get statefulset --show-labels"
abbr --add kgstsslall "kubectl get statefulset --show-labels --all-namespaces"
abbr --add kgstssln "kubectl get statefulset --show-labels --namespace"
abbr --add kgstssll "kubectl get statefulset --show-labels -l"
abbr --add kgstsw "kubectl get statefulset --watch"
abbr --add kgstswall "kubectl get statefulset --watch --all-namespaces"
abbr --add kgstswn "kubectl get statefulset --watch --namespace"
abbr --add kgstswl "kubectl get statefulset --watch -l"
abbr --add kgsvc "kubectl get service"
abbr --add kgsvcall "kubectl get service --all-namespaces"
abbr --add kgsvcn "kubectl get service --namespace"
abbr --add kgsvcl "kubectl get service -l"
abbr --add kgsvcoyaml "kubectl get service -o=yaml"
abbr --add kgsvcoyamlall "kubectl get service -o=yaml --all-namespaces"
abbr --add kgsvcoyamln "kubectl get service -o=yaml --namespace"
abbr --add kgsvcoyamll "kubectl get service -o=yaml -l"
abbr --add kgsvcowide "kubectl get service -o=wide"
abbr --add kgsvcowideall "kubectl get service -o=wide --all-namespaces"
abbr --add kgsvcowiden "kubectl get service -o=wide --namespace"
abbr --add kgsvcowidel "kubectl get service -o=wide -l"
abbr --add kgsvcojson "kubectl get service -o=json"
abbr --add kgsvcojsonall "kubectl get service -o=json --all-namespaces"
abbr --add kgsvcojsonn "kubectl get service -o=json --namespace"
abbr --add kgsvcojsonl "kubectl get service -o=json -l"
abbr --add kgsvcsl "kubectl get service --show-labels"
abbr --add kgsvcslall "kubectl get service --show-labels --all-namespaces"
abbr --add kgsvcsln "kubectl get service --show-labels --namespace"
abbr --add kgsvcsll "kubectl get service --show-labels -l"
abbr --add kgsvcw "kubectl get service --watch"
abbr --add kgsvcwall "kubectl get service --watch --all-namespaces"
abbr --add kgsvcwn "kubectl get service --watch --namespace"
abbr --add kgsvcwl "kubectl get service --watch -l"
abbr --add kging "kubectl get ingress"
abbr --add kgingall "kubectl get ingress --all-namespaces"
abbr --add kgingn "kubectl get ingress --namespace"
abbr --add kgingl "kubectl get ingress -l"
abbr --add kgingoyaml "kubectl get ingress -o=yaml"
abbr --add kgingoyamlall "kubectl get ingress -o=yaml --all-namespaces"
abbr --add kgingoyamln "kubectl get ingress -o=yaml --namespace"
abbr --add kgingoyamll "kubectl get ingress -o=yaml -l"
abbr --add kgingowide "kubectl get ingress -o=wide"
abbr --add kgingowideall "kubectl get ingress -o=wide --all-namespaces"
abbr --add kgingowiden "kubectl get ingress -o=wide --namespace"
abbr --add kgingowidel "kubectl get ingress -o=wide -l"
abbr --add kgingojson "kubectl get ingress -o=json"
abbr --add kgingojsonall "kubectl get ingress -o=json --all-namespaces"
abbr --add kgingojsonn "kubectl get ingress -o=json --namespace"
abbr --add kgingojsonl "kubectl get ingress -o=json -l"
abbr --add kgingsl "kubectl get ingress --show-labels"
abbr --add kgingslall "kubectl get ingress --show-labels --all-namespaces"
abbr --add kgingsln "kubectl get ingress --show-labels --namespace"
abbr --add kgingsll "kubectl get ingress --show-labels -l"
abbr --add kgingw "kubectl get ingress --watch"
abbr --add kgingwall "kubectl get ingress --watch --all-namespaces"
abbr --add kgingwn "kubectl get ingress --watch --namespace"
abbr --add kgingwl "kubectl get ingress --watch -l"
abbr --add kgcm "kubectl get configmap"
abbr --add kgcmall "kubectl get configmap --all-namespaces"
abbr --add kgcmn "kubectl get configmap --namespace"
abbr --add kgcml "kubectl get configmap -l"
abbr --add kgcmoyaml "kubectl get configmap -o=yaml"
abbr --add kgcmoyamlall "kubectl get configmap -o=yaml --all-namespaces"
abbr --add kgcmoyamln "kubectl get configmap -o=yaml --namespace"
abbr --add kgcmoyamll "kubectl get configmap -o=yaml -l"
abbr --add kgcmowide "kubectl get configmap -o=wide"
abbr --add kgcmowideall "kubectl get configmap -o=wide --all-namespaces"
abbr --add kgcmowiden "kubectl get configmap -o=wide --namespace"
abbr --add kgcmowidel "kubectl get configmap -o=wide -l"
abbr --add kgcmojson "kubectl get configmap -o=json"
abbr --add kgcmojsonall "kubectl get configmap -o=json --all-namespaces"
abbr --add kgcmojsonn "kubectl get configmap -o=json --namespace"
abbr --add kgcmojsonl "kubectl get configmap -o=json -l"
abbr --add kgcmsl "kubectl get configmap --show-labels"
abbr --add kgcmslall "kubectl get configmap --show-labels --all-namespaces"
abbr --add kgcmsln "kubectl get configmap --show-labels --namespace"
abbr --add kgcmsll "kubectl get configmap --show-labels -l"
abbr --add kgcmw "kubectl get configmap --watch"
abbr --add kgcmwall "kubectl get configmap --watch --all-namespaces"
abbr --add kgcmwn "kubectl get configmap --watch --namespace"
abbr --add kgcmwl "kubectl get configmap --watch -l"
abbr --add kgsec "kubectl get secret"
abbr --add kgsecall "kubectl get secret --all-namespaces"
abbr --add kgsecn "kubectl get secret --namespace"
abbr --add kgsecl "kubectl get secret -l"
abbr --add kgsecoyaml "kubectl get secret -o=yaml"
abbr --add kgsecoyamlall "kubectl get secret -o=yaml --all-namespaces"
abbr --add kgsecoyamln "kubectl get secret -o=yaml --namespace"
abbr --add kgsecoyamll "kubectl get secret -o=yaml -l"
abbr --add kgsecowide "kubectl get secret -o=wide"
abbr --add kgsecowideall "kubectl get secret -o=wide --all-namespaces"
abbr --add kgsecowiden "kubectl get secret -o=wide --namespace"
abbr --add kgsecowidel "kubectl get secret -o=wide -l"
abbr --add kgsecojson "kubectl get secret -o=json"
abbr --add kgsecojsonall "kubectl get secret -o=json --all-namespaces"
abbr --add kgsecojsonn "kubectl get secret -o=json --namespace"
abbr --add kgsecojsonl "kubectl get secret -o=json -l"
abbr --add kgsecsl "kubectl get secret --show-labels"
abbr --add kgsecslall "kubectl get secret --show-labels --all-namespaces"
abbr --add kgsecsln "kubectl get secret --show-labels --namespace"
abbr --add kgsecsll "kubectl get secret --show-labels -l"
abbr --add kgsecw "kubectl get secret --watch"
abbr --add kgsecwall "kubectl get secret --watch --all-namespaces"
abbr --add kgsecwn "kubectl get secret --watch --namespace"
abbr --add kgsecwl "kubectl get secret --watch -l"
abbr --add kgpoallowidesl "kubectl get pods --all-namespaces -o=wide --show-labels"
abbr --add kgposlowideall "kubectl get pods --show-labels -o=wide --all-namespaces"
abbr --add kgdepallowidesl "kubectl get deployment --all-namespaces -o=wide --show-labels"
abbr --add kgdepslowideall "kubectl get deployment --show-labels -o=wide --all-namespaces"
abbr --add kgstsallowidesl "kubectl get statefulset --all-namespaces -o=wide --show-labels"
abbr --add kgstsslowideall "kubectl get statefulset --show-labels -o=wide --all-namespaces"
abbr --add kgsvcallowidesl "kubectl get service --all-namespaces -o=wide --show-labels"
abbr --add kgsvcslowideall "kubectl get service --show-labels -o=wide --all-namespaces"
abbr --add kgingallowidesl "kubectl get ingress --all-namespaces -o=wide --show-labels"
abbr --add kgingslowideall "kubectl get ingress --show-labels -o=wide --all-namespaces"
abbr --add kgcmallowidesl "kubectl get configmap --all-namespaces -o=wide --show-labels"
abbr --add kgcmslowideall "kubectl get configmap --show-labels -o=wide --all-namespaces"
abbr --add kgsecallowidesl "kubectl get secret --all-namespaces -o=wide --show-labels"
abbr --add kgsecslowideall "kubectl get secret --show-labels -o=wide --all-namespaces"

# ── 基础 describe ──
abbr --add kd "kubectl describe"
abbr --add kdl "kubectl describe -l"
abbr --add kdpo "kubectl describe pods"
abbr --add kdpoall "kubectl describe pods --all-namespaces"
abbr --add kdpon "kubectl describe pods --namespace"
abbr --add kdpol "kubectl describe pods -l"
abbr --add kddep "kubectl describe deployment"
abbr --add kddepall "kubectl describe deployment --all-namespaces"
abbr --add kddepn "kubectl describe deployment --namespace"
abbr --add kddepl "kubectl describe deployment -l"
abbr --add kdsts "kubectl describe statefulset"
abbr --add kdstsall "kubectl describe statefulset --all-namespaces"
abbr --add kdstsn "kubectl describe statefulset --namespace"
abbr --add kdstsl "kubectl describe statefulset -l"
abbr --add kdsvc "kubectl describe service"
abbr --add kdsvcall "kubectl describe service --all-namespaces"
abbr --add kdsvcn "kubectl describe service --namespace"
abbr --add kdsvcl "kubectl describe service -l"
abbr --add kding "kubectl describe ingress"
abbr --add kdingall "kubectl describe ingress --all-namespaces"
abbr --add kdingn "kubectl describe ingress --namespace"
abbr --add kdingl "kubectl describe ingress -l"
abbr --add kdcm "kubectl describe configmap"
abbr --add kdcmall "kubectl describe configmap --all-namespaces"
abbr --add kdcmn "kubectl describe configmap --namespace"
abbr --add kdcml "kubectl describe configmap -l"
abbr --add kdsec "kubectl describe secret"
abbr --add kdsecall "kubectl describe secret --all-namespaces"
abbr --add kdsecn "kubectl describe secret --namespace"
abbr --add kdsecl "kubectl describe secret -l"

# ── 基础 delete ──
abbr --add kdel "kubectl delete"
abbr --add kdell "kubectl delete -l"
abbr --add kdelpo "kubectl delete pods"
abbr --add kdelpon "kubectl delete pods --namespace"
abbr --add kdelpol "kubectl delete pods -l"
abbr --add kdeldep "kubectl delete deployment"
abbr --add kdeldepn "kubectl delete deployment --namespace"
abbr --add kdeldepl "kubectl delete deployment -l"
abbr --add kdelsts "kubectl delete statefulset"
abbr --add kdelstsn "kubectl delete statefulset --namespace"
abbr --add kdelstsl "kubectl delete statefulset -l"
abbr --add kdelsvc "kubectl delete service"
abbr --add kdelsvcn "kubectl delete service --namespace"
abbr --add kdelsvcl "kubectl delete service -l"
abbr --add kdeling "kubectl delete ingress"
abbr --add kdelingn "kubectl delete ingress --namespace"
abbr --add kdelingl "kubectl delete ingress -l"
abbr --add kdelcm "kubectl delete configmap"
abbr --add kdelcmn "kubectl delete configmap --namespace"
abbr --add kdelcml "kubectl delete configmap -l"
abbr --add kdelsec "kubectl delete secret"
abbr --add kdelsecn "kubectl delete secret --namespace"
abbr --add kdelsecl "kubectl delete secret -l"

# ── kube-system 格式组合 ──
abbr --add ksysgoyaml "kubectl get --namespace=kube-system -o=yaml"
abbr --add ksysgowide "kubectl get --namespace=kube-system -o=wide"
abbr --add ksysgojson "kubectl get --namespace=kube-system -o=json"
abbr --add ksysgsl "kubectl get --namespace=kube-system --show-labels"
abbr --add ksysgw "kubectl get --namespace=kube-system --watch"
abbr --add ksysgoyamll "kubectl --namespace=kube-system get -o=yaml -l"
abbr --add ksysgoyamlf "kubectl --namespace=kube-system get -o=yaml --recursive -f"
abbr --add ksysgowidel "kubectl --namespace=kube-system get -o=wide -l"
abbr --add ksysgowidef "kubectl --namespace=kube-system get -o=wide --recursive -f"
abbr --add ksysgojsonl "kubectl --namespace=kube-system get -o=json -l"
abbr --add ksysgojsonf "kubectl --namespace=kube-system get -o=json --recursive -f"
abbr --add ksysgsll "kubectl --namespace=kube-system get --show-labels -l"
abbr --add ksysgslf "kubectl --namespace=kube-system get --show-labels --recursive -f"
abbr --add ksysgwl "kubectl --namespace=kube-system get --watch -l"
abbr --add ksysgwf "kubectl --namespace=kube-system get --watch --recursive -f"

# ── --namespace 参数版本 ──
abbr --add kgn "kubectl get --namespace"
abbr --add kdn "kubectl describe --namespace"
abbr --add kdeln "kubectl delete --namespace"
abbr --add kgno "kubectl get nodes"
abbr --add kgnon "kubectl get nodes --namespace"
abbr --add kgnol "kubectl get nodes -l"
abbr --add kgnooyaml "kubectl get nodes -o=yaml"
abbr --add kgnooyamln "kubectl get nodes -o=yaml --namespace"
abbr --add kgnooyamll "kubectl get nodes -o=yaml -l"
abbr --add kgnoowide "kubectl get nodes -o=wide"
abbr --add kgnoowiden "kubectl get nodes -o=wide --namespace"
abbr --add kgnoowidel "kubectl get nodes -o=wide -l"
abbr --add kgnoojson "kubectl get nodes -o=json"
abbr --add kgnoojsonn "kubectl get nodes -o=json --namespace"
abbr --add kgnoojsonl "kubectl get nodes -o=json -l"
abbr --add kgnosl "kubectl get nodes --show-labels"
abbr --add kgnosln "kubectl get nodes --show-labels --namespace"
abbr --add kgnosll "kubectl get nodes --show-labels -l"
abbr --add kgnow "kubectl get nodes --watch"
abbr --add kgnown "kubectl get nodes --watch --namespace"
abbr --add kgnowl "kubectl get nodes --watch -l"
abbr --add kgns "kubectl get namespaces"
abbr --add kgnsn "kubectl get namespaces --namespace"
abbr --add kgnsl "kubectl get namespaces -l"
abbr --add kgnsoyaml "kubectl get namespaces -o=yaml"
abbr --add kgnsoyamln "kubectl get namespaces -o=yaml --namespace"
abbr --add kgnsoyamll "kubectl get namespaces -o=yaml -l"
abbr --add kgnsowide "kubectl get namespaces -o=wide"
abbr --add kgnsowiden "kubectl get namespaces -o=wide --namespace"
abbr --add kgnsowidel "kubectl get namespaces -o=wide -l"
abbr --add kgnsojson "kubectl get namespaces -o=json"
abbr --add kgnsojsonn "kubectl get namespaces -o=json --namespace"
abbr --add kgnsojsonl "kubectl get namespaces -o=json -l"
abbr --add kgnssl "kubectl get namespaces --show-labels"
abbr --add kgnssln "kubectl get namespaces --show-labels --namespace"
abbr --add kgnssll "kubectl get namespaces --show-labels -l"
abbr --add kgnsw "kubectl get namespaces --watch"
abbr --add kgnswn "kubectl get namespaces --watch --namespace"
abbr --add kgnswl "kubectl get namespaces --watch -l"
abbr --add kdno "kubectl describe nodes"
abbr --add kdnon "kubectl describe nodes --namespace"
abbr --add kdnol "kubectl describe nodes -l"
abbr --add kdns "kubectl describe namespaces"
abbr --add kdnsn "kubectl describe namespaces --namespace"
abbr --add kdnsl "kubectl describe namespaces -l"
abbr --add kdelns "kubectl delete namespaces"
abbr --add kdelnsn "kubectl delete namespaces --namespace"
abbr --add kdelnsl "kubectl delete namespaces -l"

# ── kubectl edit ──
abbr --add ked "kubectl edit"
abbr --add kedn "kubectl edit --namespace"

# ── kubectl rollout ──
abbr --add kroll "kubectl rollout"
abbr --add krollrestart "kubectl rollout restart"
abbr --add krollstatus "kubectl rollout status"
abbr --add krollhistory "kubectl rollout history"
abbr --add krollundo "kubectl rollout undo"
abbr --add krr "kubectl rollout restart"

# ── kubectl top ──
abbr --add ktop "kubectl top"
abbr --add ksystop "kubectl top --namespace=kube-system"

# ── context / namespace 切换 ──
abbr --add kctx "kubectl config use-context"
abbr --add kns "kubectl config set-context --current --namespace"

# ── 节点管理 ──
abbr --add kdrain "kubectl drain"
abbr --add kcordon "kubectl cordon"
abbr --add kuncordon "kubectl uncordon"

# ── 标签 / 注解 ──
abbr --add klabel "kubectl label"
abbr --add kannotate "kubectl annotate"

# ── 文件复制 ──
abbr --add kcp "kubectl cp"

# ── 其他 ──
abbr --add ksys "kubectl --namespace=kube-system"
